services:
  - type: web
    name: shopify-wa-backend
    env: node
    buildCommand: "npm ci && npm run migrate && npm run seed"
    startCommand: "node server.js"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase: shopify-neon-db
